import "../pug/components/_ui/sliders/top-banner/top-banner-slider";
import "../pug/components/_ui/sliders/base-cards-slider/base-cards-slider";
import "../pug/components/_ui/sliders/staff-preview-slider/staff-preview-slider";
import "../pug/components/_ui/accordeon/accordeon";
import "../pug/components/_ui/nav/top-menu/top-menu";
import "./modules/scroll-up-btn";
import "./modules/input-number-mask";
import "../pug/components/_ui/tags/tags";
import "../pug/components/blocks/sidemenu/sidemenu";
import "./modules/table-wrapper";
// import "../pug/components/_ui/forms/callback-form/callback-form-height";
